/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as ReportSessionIdRouteImport } from './routes/report.$sessionId'
import { Route as PrepareUseCaseRouteImport } from './routes/prepare.$useCase'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSessionIdRoute = ReportSessionIdRouteImport.update({
  id: '/report/$sessionId',
  path: '/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareUseCaseRoute = PrepareUseCaseRouteImport.update({
  id: '/prepare/$useCase',
  path: '/prepare/$useCase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/prepare/$useCase': typeof PrepareUseCaseRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/prepare/$useCase': typeof PrepareUseCaseRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/prepare/$useCase': typeof PrepareUseCaseRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/prepare/$useCase'
    | '/report/$sessionId'
    | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/prepare/$useCase'
    | '/report/$sessionId'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/prepare/$useCase'
    | '/report/$sessionId'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrepareUseCaseRoute: typeof PrepareUseCaseRoute
  ReportSessionIdRoute: typeof ReportSessionIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$sessionId': {
      id: '/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof ReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare/$useCase': {
      id: '/prepare/$useCase'
      path: '/prepare/$useCase'
      fullPath: '/prepare/$useCase'
      preLoaderRoute: typeof PrepareUseCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrepareUseCaseRoute: PrepareUseCaseRoute,
  ReportSessionIdRoute: ReportSessionIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
